HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%89%8D%E9%94%8B&arrStation=%E9%A9%AC%E9%9E%8D%E5%B1%B1&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10e16b550>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%8A%A0%E6%A0%BC%E8%BE%BE%E5%A5%87&arrStation=%E5%B7%A8%E5%AE%9D&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x113513d68>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%8C%85%E5%A4%B4%E4%B8%9C&arrStation=%E6%BD%8D%E5%9D%8A&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x113979470>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%8C%85%E5%A4%B4&arrStation=%E6%B0%91%E6%9D%83%E5%8C%97&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1137d91d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%89%8D%E8%BF%9B%E9%95%87&arrStation=%E4%B9%8C%E5%B0%94%E6%97%97%E6%B1%97&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x114057cf8>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%89%8D%E8%BF%9B%E9%95%87&arrStation=%E5%87%A4%E5%87%B0%E5%9F%8E&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x114172828>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%89%8D%E8%BF%9B%E9%95%87&arrStation=%E5%8D%97%E6%B1%9F%E5%8F%A3&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x114028ef0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%89%8D%E8%BF%9B%E9%95%87&arrStation=%E4%BC%8A%E6%95%8F&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x114057518>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%89%8D%E8%BF%9B%E9%95%87&arrStation=%E5%A4%A7%E5%A0%A1&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1141c69e8>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%89%8D%E8%BF%9B%E9%95%87&arrStation=%E5%B9%B3%E5%8E%9F%E5%A0%A1&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1142386d8>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%89%8D%E8%BF%9B%E9%95%87&arrStation=%E6%B0%B8%E4%BF%AE&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x114084d30>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%89%8D%E8%BF%9B%E9%95%87&arrStation=%E6%B3%95%E5%90%AF&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1140c31d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%89%8D%E8%BF%9B%E9%95%87&arrStation=%E6%B8%AD%E5%8D%97%E5%8C%97&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1141e9400>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%89%8D%E8%BF%9B%E9%95%87&arrStation=%E7%8B%AC%E5%B1%B1&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x114062f28>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%89%8D%E8%BF%9B%E9%95%87&arrStation=%E7%9B%90%E5%9F%8E&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x114249278>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%89%8D%E8%BF%9B%E9%95%87&arrStation=%E8%8A%A8%E5%B2%AD&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1137bf550>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%89%8D%E8%BF%9B%E9%95%87&arrStation=%E7%B2%BE%E6%B2%B3&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x114183780>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%89%8D%E8%BF%9B%E9%95%87&arrStation=%E8%BE%BD%E9%98%B3&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11421f320>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%89%8D%E8%BF%9B%E9%95%87&arrStation=%E9%99%B5%E5%9F%8E&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11422ba90>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%89%8D%E9%94%8B&arrStation=%E4%B8%89%E4%B9%89%E4%BA%95&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x113d28eb8>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%89%8D%E8%BF%9B%E9%95%87&arrStation=%E9%AD%8F%E6%9D%96%E5%AD%90&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x113be2518>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%89%8D%E9%94%8B&arrStation=%E5%A4%AA%E5%8E%9F%E5%8C%97&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1142632e8>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%89%8D%E9%94%8B&arrStation=%E5%9D%82%E7%94%B0&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x113c14e48>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%89%8D%E9%94%8B&arrStation=%E5%B3%A8%E7%9C%89&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x114249588>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%89%8D%E9%94%8B&arrStation=%E5%BA%93%E9%83%BD%E5%B0%94&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1140d46d8>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%89%8D%E9%94%8B&arrStation=%E6%AD%99%E5%8E%BF%E5%8C%97&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x114057278>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%89%8D%E9%94%8B&arrStation=%E6%B6%9E%E6%BA%90&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1141c6588>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%89%8D%E9%94%8B&arrStation=%E7%99%BD%E6%97%97&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11428c4e0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%89%8D%E9%94%8B&arrStation=%E6%B2%82%E5%8D%97&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11403d1d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%89%8D%E9%94%8B&arrStation=%E8%B4%BA%E8%83%9C%E6%A1%A5%E4%B8%9C&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x114057f98>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%89%8D%E9%94%8B&arrStation=%E8%91%A1%E8%90%84%E8%8F%81&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1140ac4a8>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%89%8D%E9%94%8B&arrStation=%E7%BE%8A%E8%8D%89&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11417cf60>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%89%8D%E9%94%8B&arrStation=%E9%84%82%E5%B0%94%E5%A4%9A%E6%96%AF&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1141e0080>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%89%8D%E9%94%8B&arrStation=%E9%98%9C%E5%AE%81&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x113218908>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%89%8D%E9%94%8B&arrStation=%E9%A1%BA%E6%98%8C&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11403dfd0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%8A%A0%E6%A0%BC%E8%BE%BE%E5%A5%87&arrStation=%E5%81%8F%E5%B2%AD&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x113f42cc0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%8A%A0%E6%A0%BC%E8%BE%BE%E5%A5%87&arrStation=%E4%B9%9D%E5%8F%B0%E5%8D%97&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1140e5e10>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%8A%A0%E6%A0%BC%E8%BE%BE%E5%A5%87&arrStation=%E5%89%8D%E8%8B%87%E5%A1%98&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11428c080>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%8A%A0%E6%A0%BC%E8%BE%BE%E5%A5%87&arrStation=%E5%A4%A7%E7%9F%B3%E6%A1%A5&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1140c3080>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%8A%A0%E6%A0%BC%E8%BE%BE%E5%A5%87&arrStation=%E5%95%86%E9%83%BD&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x114103e48>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%8A%A0%E6%A0%BC%E8%BE%BE%E5%A5%87&arrStation=%E5%B0%8F%E8%91%A3&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x113305978>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%8A%A0%E6%A0%BC%E8%BE%BE%E5%A5%87&arrStation=%E5%BE%90%E5%B7%9E%E4%B8%9C&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11420bc50>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%8A%A0%E6%A0%BC%E8%BE%BE%E5%A5%87&arrStation=%E6%96%B0%E5%9F%8E%E5%AD%90&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x114062518>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%8A%A0%E6%A0%BC%E8%BE%BE%E5%A5%87&arrStation=%E6%9B%B9%E5%AD%90%E9%87%8C&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1141c6128>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%8A%A0%E6%A0%BC%E8%BE%BE%E5%A5%87&arrStation=%E6%A1%90%E5%AD%90%E6%9E%97&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1140964e0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%8A%A0%E6%A0%BC%E8%BE%BE%E5%A5%87&arrStation=%E6%B1%89%E5%AF%BF&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x113fbc668>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%8A%A0%E6%A0%BC%E8%BE%BE%E5%A5%87&arrStation=%E6%BB%95%E5%B7%9E%E4%B8%9C&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11336c6d8>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%8A%A0%E6%A0%BC%E8%BE%BE%E5%A5%87&arrStation=%E7%8F%AD%E7%8C%AB%E7%AE%90&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11421f860>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%8A%A0%E6%A0%BC%E8%BE%BE%E5%A5%87&arrStation=%E7%9F%B3%E6%9E%97&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1141188d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%8A%A0%E6%A0%BC%E8%BE%BE%E5%A5%87&arrStation=%E7%BA%A2%E6%9E%9C&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1140286d8>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%8A%A0%E6%A0%BC%E8%BE%BE%E5%A5%87&arrStation=%E8%8C%82%E8%88%8D%E7%A5%96&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x114238080>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%8A%A0%E6%A0%BC%E8%BE%BE%E5%A5%87&arrStation=%E9%BA%BB%E5%9F%8E%E5%8C%97&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1141c6828>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%8B%83%E5%88%A9&arrStation=%E4%B8%89%E6%B1%9F%E5%8E%BF&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1134cc908>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%8B%83%E5%88%A9&arrStation=%E5%86%8C%E4%BA%A8&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x114207400>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%8B%83%E5%88%A9&arrStation=%E4%B8%B4%E9%A2%8D&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11418e6d8>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%8B%83%E5%88%A9&arrStation=%E4%BB%99%E6%B8%B8&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1131dc470>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%8B%83%E5%88%A9&arrStation=%E5%8D%97%E5%B2%94&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1140caac8>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%8B%83%E5%88%A9&arrStation=%E5%A8%81%E7%AE%90&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x114028c50>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%8B%83%E5%88%A9&arrStation=%E5%AE%A3%E5%92%8C&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x113e5ba20>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%8B%83%E5%88%A9&arrStation=%E5%BB%BA%E7%93%AF%E8%A5%BF&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x114070ac8>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%8B%83%E5%88%A9&arrStation=%E5%B8%A6%E5%B2%AD&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x113e2b748>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%8B%83%E5%88%A9&arrStation=%E6%98%8E%E6%B8%AF&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11403da90>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%8B%83%E5%88%A9&arrStation=%E6%AD%AA%E5%A4%B4%E5%B1%B1&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11422be10>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%8B%83%E5%88%A9&arrStation=%E7%A7%A6%E7%9A%87%E5%B2%9B&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x114161160>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%8B%83%E5%88%A9&arrStation=%E7%99%BD%E9%9F%B3%E4%BB%96%E6%8B%89&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1133ef438>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%8B%83%E5%88%A9&arrStation=%E8%9A%8C%E5%9F%A0&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1139e8780>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%8B%83%E5%88%A9&arrStation=%E8%BD%AE%E5%8F%B0&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1140ac208>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%8B%83%E5%88%A9&arrStation=%E9%87%91%E6%B2%9F%E5%B1%AF&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x113ed8f98>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%8B%83%E5%88%A9&arrStation=%E9%AB%98%E5%AF%86&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1138db128>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%8B%89%E5%8E%BF&arrStation=%E5%8F%A5%E5%AE%B9%E8%A5%BF&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x114043d30>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%8B%89%E5%8E%BF&arrStation=%E5%85%AC%E4%B8%BB%E5%B2%AD&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x114253978>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%8B%89%E5%8E%BF&arrStation=%E5%9B%AD%E5%A2%A9&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x113c98898>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%8B%89%E5%8E%BF&arrStation=%E5%AE%89%E9%99%86&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x113999128>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%8B%89%E5%8E%BF&arrStation=%E5%B9%BF%E5%B7%9E%E5%8D%97&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1139680b8>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%8B%89%E5%8E%BF&arrStation=%E5%B1%B1%E6%B2%B3%E5%B1%AF&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x114043fd0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%8B%89%E5%8E%BF&arrStation=%E6%96%B0%E7%BB%B0%E6%BA%90&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x114043a90>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%8B%89%E5%8E%BF&arrStation=%E6%9D%A5%E5%AE%BE%E5%8C%97&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x113eb7550>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%8B%89%E5%8E%BF&arrStation=%E6%B1%A4%E9%98%B4&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x114043320>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%8B%89%E5%8E%BF&arrStation=%E7%BE%8A%E8%80%85%E7%AA%9D&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1138f2b00>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%8B%89%E5%8E%BF&arrStation=%E7%A4%BC%E6%B3%89&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1140dd198>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%8B%89%E5%8E%BF&arrStation=%E8%B1%86%E7%BD%97&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x113a27908>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%8B%89%E5%8E%BF&arrStation=%E9%95%BF%E6%B2%BB%E5%8C%97&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1135e6550>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%8C%85%E5%A4%B4&arrStation=%E4%BD%99%E5%A7%9A%E5%8C%97&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1140e5b00>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%8C%85%E5%A4%B4&arrStation=%E4%B9%8C%E6%8B%89%E7%89%B9%E5%89%8D%E6%97%97&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x113e7a978>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%8C%85%E5%A4%B4&arrStation=%E4%B8%9C%E4%B9%A1&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x113ce1be0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%8C%85%E5%A4%B4&arrStation=%E5%88%80%E5%B0%94%E7%99%BB&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1141b77f0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%8C%85%E5%A4%B4&arrStation=%E5%93%88%E5%AF%86&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x114138a90>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%8C%85%E5%A4%B4&arrStation=%E5%8D%97%E9%9B%84&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x113e4c3c8>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%8C%85%E5%A4%B4&arrStation=%E5%AD%9D%E6%84%9F%E5%8C%97&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1140577b8>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%8C%85%E5%A4%B4&arrStation=%E6%96%87%E6%98%8C&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1141e0a90>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%8C%85%E5%A4%B4&arrStation=%E5%B9%B3%E5%8F%B0&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x114118ba8>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%8C%85%E5%A4%B4&arrStation=%E5%BC%A5%E5%8B%92&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x113e36748>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%8C%85%E5%A4%B4&arrStation=%E6%99%AF%E6%B3%B0&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x113eca828>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%8C%85%E5%A4%B4&arrStation=%E6%A1%82%E5%B9%B3&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1140629e8>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%8C%85%E5%A4%B4&arrStation=%E7%8E%89%E7%9F%B3&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x113aa16d8>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%8C%85%E5%A4%B4&arrStation=%E6%B9%98%E6%BD%AD%E5%8C%97&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11425c3c8>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%8C%85%E5%A4%B4&arrStation=%E7%B9%81%E5%B3%99&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x113ce1550>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%8C%85%E5%A4%B4&arrStation=%E9%80%9A%E5%8C%97&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1134d3470>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%8C%85%E5%A4%B4&arrStation=%E8%8B%8D%E7%9F%B3&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11422b550>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%8C%85%E5%A4%B4&arrStation=%E9%9A%8F%E5%B7%9E&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x114057a58>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%8C%85%E5%A4%B4&arrStation=%E9%94%A6%E5%B7%9E%E5%8D%97&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x114043860>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%8C%85%E5%A4%B4&arrStation=%E9%B8%A1%E8%A5%BF&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11408e588>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%8C%85%E5%A4%B4%E4%B8%9C&arrStation=%E4%B8%89%E6%B1%9F%E5%8E%BF&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x113d716d8>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%8C%85%E5%A4%B4%E4%B8%9C&arrStation=%E4%B8%B4%E6%B1%BE%E8%A5%BF&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1141a3a20>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%8C%85%E5%A4%B4%E4%B8%9C&arrStation=%E5%8D%97%E5%85%85%E5%8C%97&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x113b29048>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%8C%85%E5%A4%B4%E4%B8%9C&arrStation=%E5%85%B4%E4%B9%89&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x113cd2940>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%8C%85%E5%A4%B4%E4%B8%9C&arrStation=%E5%BB%89%E6%B1%9F&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1140dd438>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%8C%85%E5%A4%B4%E4%B8%9C&arrStation=%E6%9E%97%E6%BA%90&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x114070630>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%8C%85%E5%A4%B4%E4%B8%9C&arrStation=%E5%B7%A8%E5%AE%9D&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x114140828>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%8C%85%E5%A4%B4%E4%B8%9C&arrStation=%E6%88%90%E9%83%BD%E5%8D%97&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x113e4cc18>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%8C%85%E5%A4%B4%E4%B8%9C&arrStation=%E6%98%86%E5%B1%B1&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1141614a8>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%8C%85%E5%A4%B4%E4%B8%9C&arrStation=%E7%A6%8F%E6%B3%89&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1136a9898>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%8C%85%E5%A4%B4%E4%B8%9C&arrStation=%E6%B7%B1%E5%9C%B3%E5%8C%97&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x114062278>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%8C%85%E5%A4%B4%E4%B8%9C&arrStation=%E8%82%87%E5%BA%86&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x114118128>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%8C%85%E5%A4%B4%E4%B8%9C&arrStation=%E9%87%8C%E6%9C%A8%E5%BA%97&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x113446f60>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%8C%85%E5%A4%B4%E4%B8%9C&arrStation=%E8%B5%A4%E5%A3%81%E5%8C%97&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x11373c9e8>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%8C%85%E5%A4%B4%E4%B8%9C&arrStation=%E9%BE%99%E5%B7%9D&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x113700828>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%8C%96%E5%B7%9E&arrStation=%E5%85%83%E6%B0%8F&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1140a2ac8>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%8C%96%E5%B7%9E&arrStation=%E5%98%89%E5%85%B4&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1140b7c88>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%8C%96%E5%B7%9E&arrStation=%E5%B0%BC%E6%9C%A8&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x113d8d860>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
HTTPConnectionPool(host='train.qunar.com', port=80): Max retries exceeded with url: /dict/open/s2s.do?callback=jQuery172031843804203989556_1495894108865&dptStation=%E5%8C%96%E5%B7%9E&arrStation=%E6%A2%85%E5%B7%9E&date=2017-06-20&type=normal&user=neibu&source=site&start=1&num=500&sort=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1140435c0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
